experiment_name: 'flat_price'
model_registry_name: 'flat_price_model'
fe_preprocessor_registry_name: 'flat_price_feat_eng_pipeline'
raw_table_name: 'cleaned_flats'
target_col: 'log1p_target'
data_split_config:
  val_size: 0.1
  test_size: 0.1
  random_state: 42
default_artifact_dir: 'artifacts'
run_names:
  baseline: 'baseline'
  eda: 'eda2'
  fe:
    preprocessor: 'fe_preprocessor2'
    model: 'fe_model2'
  fs: 'fs2'
  tuning:
    random: 'tuning_random2'
    tpe: 'tuning_tpe2'
    final_model: 'tuning_final_model2'
optuna:
  study_name: 'flat_price_study2'
  n_trials: 100
  db_name:
    random: 'optuna_random2.db'
    tpe: 'optuna_tpe2.db'
  

