transformers:

    poly:
      class_name: PolynomialFeatures
      prefix: 'poly.'
      params:
        degree: [2, 2]
        include_bias: false
      columns:
        - 'total_area'
        - 'kitchen_area'
        - 'ceiling_height'
    spline:
      class_name: SplineTransformer
      prefix: 'spline.'
      params:
        n_knots: 3
        degree: 3
      columns:
        - 'total_area'
        - 'kitchen_area'
        - 'ceiling_height' 
    kbins:
      class_name: KBinsDiscretizer
      prefix: 'kbins.'
      params:
        n_bins: 5
        encode: 'ordinal'
        strategy: 'uniform'
      columns:
        - 'total_area'
        - 'kitchen_area'
        - 'ceiling_height'
        - 'build_year'
    distance:
      class_name: DistanceTransformer
      prefix: 'dt.'
      params:
        point: [55.751244, 37.618423]
        in_features_names: ['latitude', 'longitude']
        out_feature_name: 'dist_to_center'
        distance_metric_name: 'haversine_dist2'
      columns: ['latitude', 'longitude']
    closest_distance:
      class_name: ClosestDistanceTransformer
      prefix: 'cdt.'
      params:
        points_csv_path: '../artifacts/fe/moscow_metro_stations.csv'
        points_features_names: ['lat', 'long']
        in_features_names: ['latitude', 'longitude']
        out_feature_name: 'dist_to_metro'
        distance_metric_name: 'haversine_dist2'
        points_prep_func_name: 'spherical_to_cartesian'
      columns: ['latitude', 'longitude']
    featuretools:
      class_name: FeatureToolsTransformer
      prefix: 'ft.'
      params:
        trans_primitives:
          - name: ScalarSubtractNumericFeature
            params: 
              value: 2024
        n_jobs: 1
      columns:
        - 'build_year'
    ordinal_encoder:
      class_name: OrdinalEncoder
      prefix: 'oe.'
      params:
      columns: 
        - 'is_apartment'
        - 'is_duplicated'
    passthrough1:
      class_name: 'PassthroughTransformer'
      prefix: ''
      params: 
        drop_cols: 
          ## identifiers (not needed)
          - 'id'
          - 'building_id'
          - 'subset'
          ## transformed to building age feature
          - 'build_year'
          ## encoded via OrdinalEncoder
          - 'is_apartment'
          - 'is_duplicated'
          ## dropped as a result of EDA correelation analysis
          - 'has_elevator' # high correlation with floors_total
          - 'living_area' # high correlation with total_area
      columns: 

    autofeat:
      class_name: AutoFeatTransformer
      prefix: 'af.'
      params:
        transformations:
          - '1/'
          - 'log'
          - 'cos'
          - 'sin'
        feateng_steps: 2
        featsel_runs: 5
        max_gb: 2
        corr_threshold: 0.7
        keep_feateng_cols: True
        pass_feateng_cols: False
        n_jobs: 1
        verbose: True
      columns:
        - 'ft.2024 - build_year'
        - 'flats_count'
        - 'total_area'
        - 'kitchen_area'
        - 'ceiling_height'
        - 'latitude'
        - 'longitude'
        - 'floors_total'
        - 'rooms'
        - 'floor'
    normalizer:
      class_name: FeatureNormaliserTransformer
      prefix: 'fnt.'
      params: 
        features_to_normalise: 
          - 'total_area'
        grouping_features:
          - 'kbins.build_year'
          - 'building_type_int'
        aggregation_method: 'mean'
      columns: 
        - 'total_area'
        - 'kbins.build_year'
        - 'building_type_int'
    catboost_encoder:
      class_name: CatBoostEncoder
      prefix: 'cbe.'
      params: 
        return_df: False
        cols:
          - 'building_type_int'
          - 'kbins.total_area'
          - 'kbins.kitchen_area'
          - 'kbins.build_year'
      columns: 
        - 'building_type_int'
        - 'kbins.total_area'
        - 'kbins.kitchen_area'
        - 'kbins.build_year'
    passthrough2:
      class_name: 'PassthroughTransformer'
      prefix: ''
      params: 
        drop_cols: 
        ## encoded via CatBoostEncoder
        - 'building_type_int'
        - 'kbins.total_area'
        - 'kbins.kitchen_area'
        - 'kbins.build_year'
      columns: 

    passthrough3:
      class_name: 'PassthroughTransformer'
      prefix: ''
      params: 
        passthrough_cols: # These features are kept in any case
        - 'flat_id'
        - 'log1p_target'
        ignore_cols: # These features are ignored when applying correlation filtering
        - 'flat_id'
        - 'log1p_target'
        corr_threshold: 0.85
      columns: 

pipeline:
    step1:
      transformers:
        - 'poly'
        - 'spline'
        - 'kbins'
        - 'featuretools'
        - 'distance'
        - 'closest_distance'
        - 'ordinal_encoder'
        - 'passthrough1'
    step2:
      transformers:
        - 'catboost_encoder'
        - 'normalizer'
        - 'autofeat'
        - 'passthrough2'
    step3:
      transformers:
        - 'passthrough3'

  

